### PR TITLE
Implement initial padding code

### PR DESCRIPTION
**Pull request by nvesely**
Got rid of `pcg_rand::Pcg32` because I didn't see the point in adding a 3rd party library. Probably should have asked you @gchers why you added it in the first place. I use `weak_rand()` because it's fast and cryptographic randomness isn't important here.

### CODE REVIEW

**Comment by nvesely** [comment]
> Instead of writing a function for each object type (e.g., get_html_padding()) it would be better to create a trait Padding with method pad(), and then impl Padding for each ObjectKind. Then we won't need to match on self.kind (line 41 in pad.rs in your PR) before padding.

I initially tried to create a `Paddable` trait, but didn't like how things were turning out. Perhaps this was a reflection of my novice Rust though; this is the first code I've written in the language. What you're saying doesn't entirely make sense since none of the variants of the `ObjectKind` enum store any associated value. Not that that couldn't be changed, which is something I'm going to try to work on in a different branch.

> can you please rename ObjectKind to ObjectType? ObjectKind sounds too vague

The reason I use `ObjectKind` is because `type` is a language reserved word. By using `ObjectKind`, the corresponding `Object` struct field name can be `kind`, which matches up nicely. If we made it `ObjectType`, it couldn't be `type`, but it could alternatively be `object_type`. I personally don't like this as much, but this is a pretty unimportant thing to me, so I'm fine with any name. I think this is why this "IpAddrKind" is used in the Rust book: https://doc.rust-lang.org/nightly/book/second-edition/ch06-01-defining-an-enum.html#defining-an-enum .

**Comment by nvesely** [comment]
Turns out you can't implement traits for variants (`impl Paddable for Object {}` does work, but then we have to use a similar match function).

```
error[E0573]: expected type, found variant `Object::HTML`
  --> src/pad.rs:56:19
   |
56 | impl Paddable for Object::HTML {
   |                   ^^^^^^^^^^^^
   |                   |
   |                   not a type
   |                   help: you can try using the variant's enum: `types::Object`
```

**Comment by gchers** [comment]
ObjectKind: agreed.

Code structure, how about this:

```rust
struct ObjectBinary {
    content: &[u8]
}
struct ObjectHTML {
    content: &[u8]       // we could even make this &str
}

...

trait Paddable {
    fn pad(&mut self, target_size: usize);
}

// The following *may* be needed when we're dealing with lists of Object-like types,
// but this depends on how we implement the main Alpaca algorithm.
trait Object {
    // getter/setter methods
}

impl Paddable for ObjectBinary {
    ...
}
```

The advantage is that it doesn't require to match on self.kind (of course, the actual match is moved to when objects are constructed). Also, there's no real need for an object constructor.
Note that we don't have many object types; for now, we have: HTML, CSS, and binary (which includes Alpaca objects if we set `content = []`). We'll probably need to add JSON and JS, but all binary objects can be padded in the same way. If at some point we decide we want to work on compressed objects, that's even better, as we'll only need ObjectBinary.
A cons is a bit of code duplication when `impl`-ing the `Object` trait, should we need it.

That said, I am fairly new to rust too, and am not sure at this stage what is best. We could also work with what you wrote, and then optimise the types later.

**Comment by gchers** [comment]
On a second thought, your solution is probably the best one, and it integrates more easily with my addition: https://github.com/camelids/libalpaca/blob/ea762b3011aea73b3a3e5274b427c08f561f4a92/src/morphing.rs#L16.

One current limitation is that padding can only be appended (as opposed to padding inserted at some point in the object), but so far we don't have object types requiring otherwise, so let's keep it that way.

Also, to generate random ASCII you could use: https://doc.rust-lang.org/rand/rand/trait.Rng.html#method.gen_ascii_chars. However, the PRNG discussion should be probably moved to another thread, see our private discussions, so that'll do for now.

**Pull request merged**
